### ISSUE TITLE
download - working with the website copy button

### ISSUE THREAD

**Issue by jdsutherland** [AndrewRadev/exercism.vim#1]
Disclaimer: I don't know vimscript very well.

The workflow for Exercism typically involves using the copy button to get a download command, e.g. `exercism download --exercise=acronym --track=ruby`.

Since vim commands must be titlecase, it's a bit of a hassle change `exercism` to `Exercism` when pasting the command into vim. I tried setting `cnoreabbrev exercism Exercism`, which seems to work fine so far.

Would it make sense to include this as part of the plugin?

**Comment by AndrewRadev** [comment]
Hm, generally, I just copy the token and type the rest of the command, but I admit an abbreviation might make it a lot easier. I don't feel comfortable adding it as a default, though. It feels too invasive and potentially surprising. For instance, if you copy some other command-line that the plugin doesn't support and try to run `:!exercism configure`, with a bang in the front to just run the command directly, it'll capitalize that one as well.

I'm guessing that it would be rare, personally, I'd just type the command in a different console, not through Vim. It just feels like something I wouldn't do by default in a *plugin*, but which seems perfectly sensible as a tip.

I'm going to write this down as a useful tip in the README and in the help files, but I'd rather not add it to the plugin itself. I definitely appreciate the suggestion, though.

As a follow-up, I'm wondering if it makes sense to have a catch-all "just run this in the command-line" if `:Exercism` encounters a command it doesn't know about. I can't provide completion for everything, though (I'd have to keep it constantly up-to-date manually), so I'm not sure if it'd be more confusing than helpful.
